"""
Topic Detail Page

Implements:
- Feature 2: AI Generated Summary (<=250 words)
- Feature 3: Key Information Extraction (rights, provisions, penalties, who benefits)
- Feature 4: AI Legal Assistant (RAG-based Q&A with chat history + source citations)
- Feature 5: Audio Summary (play + download)
"""
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parent.parent))

import streamlit as st

from backend.config import TOPICS
from backend.database import (
    init_db, get_topic_card, get_all_topic_cards,
    get_chat_history, add_chat_message, clear_chat_history,
)
from backend.qa_assistant import answer_question

init_db()

st.set_page_config(page_title="LegalX | Topic Detail", page_icon="\u2696\ufe0f", layout="wide")

# ---------------------------------------------------------------------------
# Topic selection (from session state, or fallback selector)
# ---------------------------------------------------------------------------
topic_id = st.session_state.get("selected_topic")

all_cards = get_all_topic_cards()
all_ids = [c["topic_id"] for c in all_cards]

if topic_id not in all_ids:
    st.warning("No topic selected (or this topic hasn't been generated yet). Choose one below:")
    if not all_cards:
        st.info("No topics generated yet. Go back to the home page and run the AI pipeline.")
        if st.button("\u2190 Back to Home"):
            st.switch_page("app.py")
        st.stop()

    topic_id = st.selectbox(
        "Select a topic",
        options=all_ids,
        format_func=lambda tid: TOPICS[tid]["name"],
    )
    st.session_state["selected_topic"] = topic_id

card = get_topic_card(topic_id)
topic_name = TOPICS[topic_id]["name"]

# ---------------------------------------------------------------------------
# Header / navigation
# ---------------------------------------------------------------------------
top_cols = st.columns([1, 5])
with top_cols[0]:
    if st.button("\u2190 Home"):
        st.switch_page("app.py")
with top_cols[1]:
    st.title(f"\u2696\ufe0f {topic_name}")
    st.caption(card["short_description"])

st.divider()

main_col, side_col = st.columns([2, 1])

# ---------------------------------------------------------------------------
# Feature 2: AI Generated Summary
# ---------------------------------------------------------------------------
with main_col:
    st.subheader("\U0001F4D6 Summary")
    st.write(card["summary"])
    word_count = len(card["summary"].split())
    st.caption(f"{word_count} words \u00b7 Generated by Mistral AI from source legal text")

    st.divider()

    # -----------------------------------------------------------------------
    # Feature 3: Key Information Extraction
    # -----------------------------------------------------------------------
    st.subheader("\U0001F50D Key Information")

    tabs = st.tabs(["\u2696\ufe0f Key Rights", "\U0001F4DC Important Provisions", "\u26A0\ufe0f Penalties", "\U0001F465 Who Can Benefit"])

    with tabs[0]:
        if card["key_rights"]:
            for item in card["key_rights"]:
                st.markdown(f"- {item}")
        else:
            st.info("No key rights extracted.")

    with tabs[1]:
        if card["important_provisions"]:
            for item in card["important_provisions"]:
                st.markdown(f"- {item}")
        else:
            st.info("No provisions extracted.")

    with tabs[2]:
        if card["penalties"]:
            for item in card["penalties"]:
                st.markdown(f"- {item}")
        else:
            st.info("No penalties extracted.")

    with tabs[3]:
        if card["who_benefits"]:
            for item in card["who_benefits"]:
                st.markdown(f"- {item}")
        else:
            st.info("No beneficiary information extracted.")

# ---------------------------------------------------------------------------
# Feature 5: Audio Summary
# ---------------------------------------------------------------------------
with side_col:
    st.subheader("\U0001F50A Audio Summary")
    audio_path = card.get("audio_path")
    if audio_path and Path(audio_path).exists():
        audio_bytes = Path(audio_path).read_bytes()
        st.audio(audio_bytes, format="audio/mp3")
        st.download_button(
            "\u2B07\ufe0f Download Audio",
            data=audio_bytes,
            file_name=f"{topic_id}_summary.mp3",
            mime="audio/mp3",
            use_container_width=True,
        )
    else:
        st.info("Audio not generated yet. Run the pipeline from the home page.")

    st.divider()
    st.markdown("**About this card**")
    st.caption(f"Generated: {card.get('generated_at', 'N/A')}")
    st.caption("Source: provided legal reference text (input corpus)")
    st.caption("Pipeline: Mistral AI \u2192 structured JSON \u2192 SQLite \u2192 RAG index (ChromaDB)")

st.divider()

# ---------------------------------------------------------------------------
# Feature 4: AI Legal Assistant (RAG-based Q&A)
# ---------------------------------------------------------------------------
st.subheader("\U0001F916 AI Legal Assistant")
st.caption(f"Ask a question about **{topic_name}**. Answers are generated using RAG "
           f"(Retrieval-Augmented Generation) over the topic's source text.")

# Example questions
example_qs = {
    "pocso_act": "What is the punishment for aggravated penetrative sexual assault?",
    "consumer_protection_act": "What are my rights if I buy a defective product?",
    "cyber_crime_laws": "What should I do if I am a victim of online fraud?",
    "rti_act": "Who can file an RTI request and how long does it take to get a response?",
    "gst_registration": "Who needs to register for GST?",
}
ex_q = example_qs.get(topic_id)
if ex_q:
    st.caption(f"\U0001F4A1 Example: \"{ex_q}\"")

# Render existing chat history
history = get_chat_history(topic_id)
chat_container = st.container(height=350)
with chat_container:
    if not history:
        st.markdown("_No questions asked yet for this topic._")
    for msg in history:
        with st.chat_message(msg["role"]):
            st.write(msg["content"])
            if msg["role"] == "assistant" and msg["sources"]:
                with st.expander("\U0001F4CE Sources used"):
                    st.write(", ".join(msg["sources"]))

# Chat input
user_question = st.chat_input(f"Ask a question about {topic_name}...")

col_a, col_b = st.columns([1, 5])
with col_a:
    if st.button("\U0001F5D1\ufe0f Clear chat history"):
        clear_chat_history(topic_id)
        st.rerun()

if user_question:
    add_chat_message(topic_id, "user", user_question)
    with st.spinner("Thinking... (retrieving relevant legal context via RAG)"):
        result = answer_question(topic_id, user_question, chat_history=history)
    add_chat_message(topic_id, "assistant", result["answer"], sources=result["sources"])
    st.rerun()
